openapi: 3.0.1
info:
  title: Public IP API
  description: This API allows clients to retrieve their own public IPv4 and IPv6 addresses. It's a simple and effective tool for a clients public IP address detection and troubleshooting network issues.
  termsOfService: https://ipsimple.org/terms/
  contact:
    email: support@ipsimple.org
  version: '1.0'
servers:
  - url: https://ipsimple-apim-test-eastus.azure-api.net
paths:
  /ipv4:
    get:
      summary: Public IPv4 address
      description: This endpoint returns the public IPv4 address of the client making the request.
      operationId: get-ipv4
      parameters:
        - name: format
          in: query
          schema:
            enum:
              - json
              - plain
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: 98.207.254.136
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                    example: 98.207.254.136
              example:
                ip: 98.207.254.136
        '429':
          description: Too many requests
  /ipv6:
    get:
      summary: Public IPv6 address
      description: This endpoint returns the public IPv6 address of the client making the request.
      operationId: get-ipv6
      parameters:
        - name: format
          in: query
          schema:
            enum:
              - json
              - plain
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: 2a00:1450:400f:80d::200e
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                    example: 2a00:1450:400f:80d::200e
              example:
                ip: 2a00:1450:400f:80d::200e
        '429':
          description: Too many requests
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]