name: Build & Publish Base Images

on:
  workflow_dispatch:

jobs:
  fetch-scan-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch base image
      run: |
        docker pull mcr.microsoft.com/dotnet/aspnet:8.0
        docker pull mcr.microsoft.com/dotnet/sdk:8.0

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan dotnet base image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: mcr.microsoft.com/dotnet/aspnet:8.0
        format: 'table'
        exit-code: '1' # Exit code 1 if vulnerabilities are found

    - name: Scan dotnet sdk image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: mcr.microsoft.com/dotnet/sdk:8.0
        format: 'table'
        exit-code: '1' # Exit code 1 if vulnerabilities are found

    - name: Tag and push base image to GitHub Packages
      run: |
        docker tag mcr.microsoft.com/dotnet/aspnet:8.0 ghcr.io/ipsimple/aspnet:8.0
        docker tag mcr.microsoft.com/dotnet/sdk:8.0 ghcr.io/ipsimple/sdk:8.0
        docker push ghcr.io/ipsimple/aspnet:8.0
        docker push ghcr.io/ipsimple/sdk:8.0

    - name: Generate SBOM for ASP.NET
      run: |
        syft packages docker:ghcr.io/ipsimple/aspnet:8.0 -o syft-json > sbom-aspnet.json

    - name: Generate SBOM for SDK
      run: |
        syft packages docker:ghcr.io/ipsimple/sdk:8.0 -o syft-json > sbom-sdk.json

    - name: Upload SBOM for ASP.NET
      uses: actions/upload-artifact@v2
      with:
        name: sbom-aspnet
        path: sbom-aspnet.json

    - name: Upload SBOM for SDK
      uses: actions/upload-artifact@v2
      with:
        name: sbom-sdk
        path: sbom-sdk.json
