name: Build & Publish Base Images

on:
  workflow_dispatch:

jobs:
  fetch-base-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch base image
      run: |
        docker pull mcr.microsoft.com/dotnet/aspnet:8.0
        docker pull mcr.microsoft.com/dotnet/sdk:8.0

  scan-base-images:
    runs-on: ubuntu-latest
    needs: fetch-base-images
    continue-on-error: true

    steps:
    - name: Scan dotnet base image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: mcr.microsoft.com/dotnet/aspnet:8.0
        format: 'table'
        exit-code: '1' # Exit code 1 if vulnerabilities are found

    - name: Scan dotnet sdk image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: mcr.microsoft.com/dotnet/sdk:8.0
        format: 'table'
        exit-code: '1' # Exit code 1 if vulnerabilities are found

  push-base-images:
    runs-on: ubuntu-latest
    needs: fetch-base-images

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ASP.NET base image
      id: build_aspnet
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/ipsimple/aspnet:8.0

    - name: Build and push SDK base image
      id: build_sdk
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/ipsimple/sdk:8.0

  generate-sbom:
    runs-on: ubuntu-latest
    needs: push-base-images

    steps:
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM for ASP.NET
      run: |
        syft docker:ghcr.io/ipsimple/aspnet:8.0 -o syft-json > sbom-aspnet.json

    - name: Generate SBOM for SDK
      run: |
        syft docker:ghcr.io/ipsimple/sdk:8.0 -o syft-json > sbom-sdk.json

    - name: Upload SBOM for ASP.NET
      uses: actions/upload-artifact@v2
      with:
        name: sbom-aspnet
        path: sbom-aspnet.json

    - name: Upload SBOM for SDK
      uses: actions/upload-artifact@v2
      with:
        name: sbom-sdk
        path: sbom-sdk.json

  generate-attestations:
    runs-on: ubuntu-latest
    needs: [push-base-images, generate-sbom]

    steps:
    - name: Generate SBOM attestation for ASP.NET
      uses: actions/attest-sbom@v1
      with:
        subject-name: ghcr.io/ipsimple/aspnet
        subject-digest: ${{ needs.push-base-images.outputs['build_aspnet'].digest }}
        sbom-path: sbom-aspnet.json
        push-to-registry: true

    - name: Generate SBOM attestation for SDK
      uses: actions/attest-sbom@v1
      with:
        subject-name: ghcr.io/ipsimple/sdk
        subject-digest: ${{ needs.push-base-images.outputs['build_sdk'].digest }}
        sbom-path: sbom-sdk.json
        push-to-registry: true
